services:
  node-red:
    build:
      context: ./NodeRed/ConfigurationFiles
    container_name: node-red
    user: "0"
    privileged: true
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ=Europe/Brussels
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN:?error}
      - TELEGRAM_CHATID=${TELEGRAM_CHATID:?error} 
    ports:
      - "1880:1880"
    devices:
      - /dev/gpiomem
    volumes:
      - ./NodeRed/Data:/data
    group_add:
      - dialout

  gpiod:
    image: corbosman/pigpiod
    privileged: true
    restart: unless-stopped

 # cloudflared:
 #   container_name: cloudflared
 #   image: cloudflare/cloudflared
 #   restart: unless-stopped
 #   command: tunnel run
 #   environment:
 #     - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
 #   network_mode: host
