FROM nodered/node-red:latest

WORKDIR /data
COPY package.json /data/package.json
RUN npm install --unsafe-perm --no-update-notifier --no-fund --only=production
COPY settings.js /data/settings.js
COPY flows.json /data/flows.json
RUN sudo apt install python3
RUN sudo apt install python3-RPi.GPIO