FROM nodered/node-red:latest

#USER root
#RUN apk add py3-rpigpio

USER node-red

# Add package to install
RUN npm install node-red-dashboard
RUN npm install node-red-contrib-socketcan
RUN npm install node-red-contrib-ui-led
RUN npm install js-pigpio
RUN npm install node-red-contrib-telegrambot
