FROM nodered/node-red:latest

WORKDIR /data
COPY package.json /data/package.json
RUN npm install --unsafe-perm --no-update-notifier --no-fund --only=production
WORKDIR /usr/src/node-red
COPY settings.js /data/settings.js
COPY flows.json /data/flows.json

USER root
RUN apk add py3-pip
RUN apk add py3-rpigpio
USER node-red
